# Generated by Django 6.0.3 on 2026-07-02 17:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('endereco', models.CharField(max_length=150)),
                ('telefone', models.CharField(max_length=15)),
                ('cpf', models.CharField(max_length=14, unique=True)),
                ('saldo_fiado', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('limite_fiado', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Mercadinho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('telefone', models.CharField(max_length=11)),
                ('localizacao', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('cnpj', models.CharField(max_length=18)),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('categoria', models.CharField(max_length=50)),
                ('descricao', models.TextField(blank=True)),
                ('codigo', models.CharField(max_length=30, unique=True)),
                ('marca', models.CharField(blank=True, max_length=50)),
                ('preco_venda', models.DecimalField(decimal_places=2, max_digits=10)),
                ('preco_custo', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('quantidade', models.PositiveIntegerField(default=0)),
                ('validade', models.DateField(blank=True, null=True)),
                ('fornecedor', models.CharField(blank=True, max_length=100)),
                ('status', models.BooleanField(default=True)),
                ('destaque', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forma_pagamento', models.CharField(max_length=50)),
                ('preco_produto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_compra', models.DateField(auto_now_add=True)),
                ('codigo_venda', models.CharField(max_length=20)),
                ('status_pagamento', models.CharField(max_length=50)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compras', to='core.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Possui',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(max_length=50)),
                ('validade', models.DateField()),
                ('fornecedor', models.CharField(max_length=100)),
                ('quantidade_estoque', models.IntegerField()),
                ('data_entrada_estoque', models.DateField()),
                ('mercadinho', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.mercadinho')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.produto')),
            ],
        ),
        migrations.CreateModel(
            name='ItensCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField()),
                ('compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.compra')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.produto')),
            ],
        ),
    ]
