# Generated by Django 6.0.5 on 2026-09-25 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='venda',
            name='data_pagamento_fiado',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='venda',
            name='fiado_pago',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='venda',
            name='vencimento_fiado',
            field=models.DateField(blank=True, null=True),
        ),
    ]
