# Generated by Django 6.0.5 on 2026-09-19 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_possui_estoque_remove_itenscompra_compra_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venda',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='estoque',
            name='mercadinho',
        ),
        migrations.RemoveField(
            model_name='estoque',
            name='produto',
        ),
        migrations.RemoveField(
            model_name='itemvenda',
            name='produto',
        ),
        migrations.RemoveField(
            model_name='itemvenda',
            name='venda',
        ),
        migrations.DeleteModel(
            name='Cliente',
        ),
        migrations.DeleteModel(
            name='Estoque',
        ),
        migrations.DeleteModel(
            name='Produto',
        ),
        migrations.DeleteModel(
            name='ItemVenda',
        ),
        migrations.DeleteModel(
            name='Venda',
        ),
    ]
