# Generated by Django 6.0.5 on 2026-10-03 02:19

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0004_remove_venda_cliente_remove_estoque_mercadinho_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movimentacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ENTRADA', 'Entrada'), ('SAIDA', 'Saída')], max_length=10)),
                ('descricao', models.CharField(max_length=150)),
                ('categoria', models.CharField(blank=True, max_length=80)),
                ('valor', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('data', models.DateField()),
                ('data_vencimento', models.DateField(blank=True, null=True)),
                ('forma_pagamento', models.CharField(blank=True, max_length=40)),
                ('status', models.CharField(choices=[('PAGA', 'Paga'), ('A_VENCER', 'A vencer'), ('ATRASADA', 'Atrasada')], default='PAGA', max_length=12)),
                ('referencia', models.CharField(blank=True, max_length=100)),
                ('observacao', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('mercadinho', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='movimentacoes_financeiras', to='core.mercadinho')),
            ],
            options={
                'verbose_name': 'Movimentação financeira',
                'verbose_name_plural': 'Movimentações financeiras',
                'ordering': ['-data', '-id'],
            },
        ),
    ]
