# Generated by Django 6.0.5 on 2026-09-19 19:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0004_remove_venda_cliente_remove_estoque_mercadinho_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('categoria', models.CharField(max_length=50)),
                ('descricao', models.TextField(blank=True)),
                ('codigo', models.CharField(max_length=30, unique=True)),
                ('marca', models.CharField(blank=True, max_length=50)),
                ('preco_venda', models.DecimalField(decimal_places=2, max_digits=10)),
                ('preco_custo', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('quantidade', models.PositiveIntegerField(default=0)),
                ('validade', models.DateField(blank=True, null=True)),
                ('fornecedor', models.CharField(blank=True, max_length=100)),
                ('status', models.BooleanField(default=True)),
                ('destaque', models.BooleanField(default=False)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Estoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(max_length=50)),
                ('validade', models.DateField()),
                ('fornecedor', models.CharField(max_length=100)),
                ('quantidade', models.IntegerField()),
                ('data_entrada', models.DateField()),
                ('mercadinho', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.mercadinho')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produtos.produto')),
            ],
        ),
    ]
