# Generated by Django 6.0 on 2026-10-07
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chave', models.CharField(max_length=180)),
                ('tipo', models.CharField(choices=[('estoque', 'Estoque'), ('validade', 'Validade'), ('fiado', 'Fiado'), ('financeiro', 'Financeiro')], max_length=20)),
                ('titulo', models.CharField(max_length=120)),
                ('mensagem', models.CharField(max_length=240)),
                ('url', models.CharField(blank=True, max_length=255)),
                ('prioridade', models.PositiveSmallIntegerField(default=1)),
                ('lida', models.BooleanField(default=False)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificacoes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notificação',
                'verbose_name_plural': 'Notificações',
                'ordering': ['lida', '-prioridade', '-criada_em', '-id'],
            },
        ),
        migrations.AddConstraint(
            model_name='notificacao',
            constraint=models.UniqueConstraint(fields=('usuario', 'chave'), name='uniq_notificacao_usuario_chave'),
        ),
    ]
